# Generated by Django 2.1.7 on 2022-02-10 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220210_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 2, 10, 17, 21, 56, 548361)),
        ),
    ]
